### ISSUE TITLE
`zsh-abbr` not working when the `viins` keymap is selected

### ISSUE THREAD

**Issue by tapyu** [olets/zsh-abbr#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Update the issue title

- [X] I have updated the title

### Expected Behavior

My `zle-line-init()` widget sets the the vi-like insert-mode keymap (`viins`) whenever a new command line  starts to read a new line of input. 

```
zle-keymap-select() {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[2 q' # use \e[1 to blinking
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[6 q'
  fi
}


zle-line-init() {
  zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
  # echo -ne "\e[6 q" # beam shape
}
zle -N zle-line-init
zle -N zle-keymap-select
echo -ne '\e[6 q' # Use beam shape cursor on startup. (use \e[5 for blinking beam shape
preexec() { echo -ne '\e[6 q' ;} # Use beam shape cursor for each new prompt.
```

I am not sure why, by it prevents zsh-abbr from working... Is that an unpredictable behavior?

### Actual Behavior

The VI mode works as expect, but the zsh-abbr doesn't. However, when I went back from the vicmd keymap, I can use abbr.

### Steps To Reproduce

1. Check my [`.zshrc`](https://github.com/tapyu/dotfiles/blob/main/zsh/.config/zsh/.zshrc)
2. Follow the same steps you see on the GIF
![abbr](https://github.com/olets/zsh-abbr/assets/22801918/eabf2b9f-0223-41a6-88a1-83c7635ac33f)

### Environment

```shell
❯ abbr profile
zsh-abbr version 5.1.0
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
OSTYPE linux-gnu
```

### Installation method

Manual

### Installation method details

I have my own manual way to install my plugins. Check my dotfiles for more info.

### Anything else?

I there is no incompatibility with any other plugin that I am using. AFAIK, the unique issue is with the the `viins` keymap.

**Comment by tapyu** [comment]
Yes, it worked. Thank you!

**Comment by olets** [comment]
Great! Added it to the documentation https://zsh-abbr.olets.dev/advanced.html#alternative-keymaps

**Comment by olets** [comment]
Belatedly acknowledging more contributors in https://github.com/olets/zsh-abbr#community and https://zsh-abbr.olets.dev/community/

Would you like to be added @tapyu ? If so, I'll have the all-contributors bot open a pull request. Then I'll tag you in it to review for correct info

**Comment by tapyu** [comment]
Hi!

At the moment I've been using https://github.com/MenkeTechnologies/zsh-expand instead of this repo. I kinda get used to it and I didn't have time to fiddle zsh codes so far. So I cannot be a contributor at the moment. However, if I decide to go back to this plugin and start to make PRs, I would be interested in becoming a contributor. :)
