### ISSUE TITLE
[Bug report] bad math expression: operator expected at `Jan  1 03:...'

### ISSUE THREAD

**Issue by Orest58008** [olets/zsh-abbr#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Update the issue title

- [X] I have updated the title

### Expected Behavior

abbr working

### Actual Behavior

```zsh
~
><> abbr a=b
_abbr_job_push:wait_turn:3: bad math expression: operator expected at `Jan  1 03:...'
```

### Environment

```shell
`abbr profile` also results in _abbr_job_push:wait_turn:3: bad math expression: operator expected at `Jan  1 03:...'
```

### Installation method

Plugin manager

### Installation method details

zcomet(last update as of 2023-12-31)

### Anything else?

zsh 5.9 (x86_64-pc-linux-gnu)

**Comment by olets** [comment]
Hi @Orest58008, thanks for reporting!

What output do you get for

```
echo $OSTYPE
```

**Comment by olets** [comment]
@Orest58008 I think I have the fix for this. Can you try it out? You'll need to switch zsh-abbr to the branch `106-date-format`. One way to do that for zcomet is

1. Delete the plugin directory
    ```shell
    rm -rf ${ZCOMET[REPOS_DIR]}/olets/zsh-abbr
    ```
2. In `.zshrc` change `zcomet load olets/zsh-abbr` to `zcomet load olets/zsh-abbr@106-date-format`

**Comment by Orest58008** [comment]
I believe this was a problem with my .zshrc in which I set path as `(/opt/plan9/bin ... $path)`, and couldn't unset it even after correctly setting /opt/plan9/bin after $path. Sorry to bother you if I did

**Comment by olets** [comment]
> Sorry to bother you if I did

You didn't, and in looking into it I learned something new 👍
