### ISSUE TITLE
[Bug report] Terminal "freezes" when there is no abbreviations and highlights for user abbreviations are used with zsh-syntax-highlighting

### ISSUE THREAD

**Issue by Farid-NL** [olets/zsh-abbr#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Update the issue title

- [X] I have updated the title

### Expected Behavior

Deleting characters (specifically the last one) should work as usual when using [zsh-syntax-highlighting](https://zsh-abbr.olets.dev/advanced.html#zsh-syntax-highlighting)

Example:

![example-right](https://github.com/olets/zsh-abbr/assets/34426099/4aa6e6d5-9312-4661-aa22-ddeb82d920b9)

### Actual Behavior

The last character cannot be deleted and the terminal 'freezes' (can't type, can't use widgets, etc).

To 'unfreeze' the terminal it is necessary to use CTRL-C.

![example-wrong](https://github.com/olets/zsh-abbr/assets/34426099/f38e06ea-9d33-4480-801b-d3a1284d358b)

### Steps To Reproduce

With a terminal session with at least 1 abbreviation:

1. Type anything and delete everything, char by char. It should work as expected.
2. Remove all abbreviations.
3. Run `exec zsh`.
4. Type anything and delete everything, char by char. It shouldn't work, the terminal "freezes". **<< That's the bug**
5. Use <kbd>Ctrl</kbd> + <kbd>C</kbd> to "unfreeze" the terminal.
6. Add some abbreviations.
7. Run `exec zsh`.
8. Type anything and delete everything, character by character. It should work as expected.

![bug](https://github.com/olets/zsh-abbr/assets/34426099/19a03b78-59ed-4b73-8ff8-c97da1ea73b7)

### Environment

```shell
zsh-abbr version 5.7.0
zsh 5.9 (x86_64-ubuntu-linux-gnu)
OSTYPE linux-gnu (Ubuntu)
```

### Installation method

Plugin manager

### Installation method details

**Zsh framework (Plugin manager):** [zsh4humans](https://github.com/romkatv/zsh4humans) (latest)

Installation process:

1. Add the plugin repo
    ```bash
    z4h install olets/zsh-abbr || return
    ```
2. Load the plugin
    ```bash
    z4h load olets/zsh-abbr
    ```

### Anything else?

I place the following code below where zsh-abbr is loaded:

```bash
#|---------------
#| Load plugins
#|---------------

z4h load olets/zsh-abbr

#|-------------------
#| Plugins settings
#|-------------------

#|-- zsh-syntax-highlighting --
#| zsh-abbr:
typeset -A ZSH_HIGHLIGHT_REGEXP
ZSH_HIGHLIGHT_HIGHLIGHTERS+=(regexp)
ZSH_HIGHLIGHT_REGEXP+=('^[[:blank:][:space:]]*('${(j:|:)${(Qk)ABBR_REGULAR_USER_ABBREVIATIONS}}')$' fg=blue,bold,underline)
ZSH_HIGHLIGHT_REGEXP+=('\<('${(j:|:)${(Qk)ABBR_GLOBAL_USER_ABBREVIATIONS}}')$' fg=blue,bold,underline)
```

**Comment by Farid-NL** [comment]
A workaround would be to check if `$ABBR_USER_ABBREVIATIONS_FILE` has contents:

```bash
if [[ -s "$ABBR_USER_ABBREVIATIONS_FILE" ]]; then
  typeset -A ZSH_HIGHLIGHT_REGEXP
  ZSH_HIGHLIGHT_HIGHLIGHTERS+=(regexp)
  ZSH_HIGHLIGHT_REGEXP+=('^[[:blank:][:space:]]*('${(j:|:)${(Qk)ABBR_REGULAR_USER_ABBREVIATIONS}}')$' fg=blue,bold,underline)
  ZSH_HIGHLIGHT_REGEXP+=('\<('${(j:|:)${(Qk)ABBR_GLOBAL_USER_ABBREVIATIONS}}')$' fg=blue,bold,underline)
fi
```

**Comment by olets** [comment]
Thanks for the report. Good catch!

More reliable than checking for ABBR_USER_ABBREVIATIONS_FILE file contents is to check that there's at least one user abbreviation:

```diff
- [[ -s "$ABBR_USER_ABBREVIATIONS_FILE" ]]
+ (( ${#ABBR_REGULAR_USER_ABBREVIATIONS} ))
```

I've updated the docs https://zsh-abbr.olets.dev/advanced.html#zsh-syntax-highlighting

**Comment by olets** [comment]
@Farid-NL I offer to add bug reporters to https://zsh-abbr.olets.dev/community/ and https://github.com/olets/zsh-abbr#community. Do you want to be listed? If so I'll have the all-contributors bot open a PR; you'll need to review it to make sure the info the bot pulls is correct

**Comment by Farid-NL** [comment]
Thanks for the offer, I'm good.

And thank you for such an awesome zsh plugin!
