### ISSUE TITLE
Do not follow aliases when calling system commands

### ISSUE THREAD

**Issue by allisio** [olets/zsh-abbr#13]
I recently discovered a really nice [`ls` replacement](https://the.exa.website/). Naturally, I did an `alias ls=exa` straight away... and my next terminal hung like crazy.

It turns out the problem is in [`_zsh_abbr_job_push:next_job_id()`](https://github.com/olets/zsh-abbr/blob/a0242c20df40b379f752788a84ed3a97eaa3f8fb/zsh-abbr.zsh#L975), where the behavior of `ls -t` is assumed to be constant. Unfortunately, exa's `-t` flag works very similarly, but doesn't have a default.

A straightforward fix would be to use `\ls` instead, but I don't know how that meshes with the project's practices.

**Comment by olets** [comment]
Thanks for the report!

> `alias ls=exa`

Brave. But it's a good point, `ls` is particular is one people like to alias to add options.

> use \ls instead

Wrapping system commands to prevent the use of aliases would be a maintainable solution. I have a picture of how it'll work, will look for time in the next week.

**Comment by olets** [comment]
Done! Let me know if you have more trouble. Thought I might wrap all system commands, but decided to just address `ls` for now.

**Comment by allisio** [comment]
That should definitely do it. In the meantime, I realized it would make more sense to just source my `aliases` at the end of my `zshrc`, but this looks like a very robust approach to handling "brave" aliasing. :sweat_smile: 

Thanks!

**Comment by olets** [comment]
Belatedly recognizing bug reporters in https://github.com/olets/zsh-abbr#community and https://zsh-abbr.olets.dev/community/. would you like to be added @allisio?
