### ISSUE TITLE
Sentence ends in the middle in README.md

### ISSUE THREAD

**Issue by taladar** [olets/zsh-abbr#19]
` Like fish's abbr, zsh-abbr supports interactive creation of persistent abbreviations that are immediately available in all terminal sessions and. `

**Comment by olets** [comment]
Fixed! Thanks for catching that

**Comment by olets** [comment]
Belatedly recognizing bug reporters in https://github.com/olets/zsh-abbr#community and https://zsh-abbr.olets.dev/community/. would you like to be added @taladar?

**Comment by taladar** [comment]
Thanks but I feel this was such a minor thing that is not necessary.
