### ISSUE TITLE
Possible to integrate with zsh-syntax-highlighting?

### ISSUE THREAD

**Issue by Herjar** [olets/zsh-abbr#23]
When I use an alias, e.g. `alias gst="git status"`, [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) shows if it is a valid command/alias like this:
![image](https://user-images.githubusercontent.com/3456683/93186436-ec237080-f73e-11ea-9a1a-5663166f9971.png)

When I define the same with `zsh-abbr` it looks invalid:
![image](https://user-images.githubusercontent.com/3456683/93186572-12e1a700-f73f-11ea-96a5-0a13ccbd96ae.png)

Is it possible to get the same validation with `zsh-abbr`?

**Comment by olets** [comment]
Let me know if these work for you. Works in my Ubuntu VM but it'd be nice to get that WSL2 confirmation before I add them to the README.

```shell
# in .zshrc

typeset -A ZSH_HIGHLIGHT_REGEXP
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main regexp)
# the next two lines must come after zsh-abbr
ZSH_HIGHLIGHT_REGEXP=('^[[:blank:][:space:]]*('${(j:|:)${(k)ABBR_REGULAR_USER_ABBREVIATIONS}}')$' fg=blue)
ZSH_HIGHLIGHT_REGEXP+=('\<('${(j:|:)${(k)ABBR_GLOBAL_USER_ABBREVIATIONS}}')$' fg=yellow)
```

```shell
% abbr x=test
% abbr -g y=test
```
```
% x # should be blue
```
```
% <space>x # should be blue
```
```
% <tab>x # should be blue
```
```
% a x # should not color
```
```
%
x # should be blue (alt-enter for a line break)
```
```
% a
x # should not color
```
```
% y # should be yellow
```
```
% <space>y # should be yellow
```
```
% <tab>y # should be yellow
```
```
% a y # should be yellow
```
```
%
y # should be yellow (alt-enter for a line break)
```
```
% a
y # should be yellow
```

---

You can customize the `fg=` bits to meet your needs

**Comment by Herjar** [comment]
It works great :rocket:

Thank you!

**Comment by olets** [comment]
This is now in the README!
