### ISSUE TITLE
fast-syntax-highlighting highlighting of single-word abbreviations

### ISSUE THREAD

**Issue by olets** [olets/zsh-abbr#24]
Would be nice to support [fast-syntax-highlighting](https://github.com/zdharma/fast-syntax-highlighting).

Its [chroma docs are here](https://github.com/zdharma-continuum/fast-syntax-highlighting/blob/master/CHROMA_GUIDE.adoc).

- [x] single-word abbreviations
- ~multi-word abbreviations~ tracking in #120

**Comment by tomoesaturn** [comment]
As a workaround solution, I use this code snippet at the end of `.zshrc` file to highlight for single word abbreviations.

```zsh
chroma_single_word() {
  (( next_word = 2 | 8192 ))

  local __first_call="$1" __wrd="$2" __start_pos="$3" __end_pos="$4"
  local __style

  (( __first_call )) && { __style=${FAST_THEME_NAME}command }
  [[ -n "$__style" ]] && (( __start=__start_pos-${#PREBUFFER}, __end=__end_pos-${#PREBUFFER}, __start >= 0 )) && reply+=("$__start $__end ${FAST_HIGHLIGHT_STYLES[$__style]}")

  (( this_word = next_word ))
  _start_pos=$_end_pos

  return 0
}

# register single word command execpt for the followings:
# - already in PATH
# - already in fast-syntax-highlighting chroma map
register_single_word_chroma() {
  local word=$1
  if [[ -x $(command -v $word) ]] || [[ -n $FAST_HIGHLIGHT["chroma-$word"] ]]; then
    return 1
  fi

  FAST_HIGHLIGHT+=( "chroma-$word" chroma_single_word )
  return 0
}


if [[ -n $FAST_HIGHLIGHT ]]; then

  for abbr in ${(f)"$(abbr list-abbreviations)"}; do
    if [[ $abbr != *' '* ]]; then
      register_single_word_chroma ${(Q)abbr}
    fi
  done

fi

```

**Comment by olets** [comment]
@tomoesaturn what an exciting notification to receive! Thanks for sharing. Looks like it works.

My intuition would be to use `${FAST_THEME_NAME}alias` not `${FAST_THEME_NAME}command`. If you considered that, what made you choose `${FAST_THEME_NAME}command`?

How hard do you think it would be to support multi-word abbreviations? Is that possible with F-Sy-H?

**Comment by tomoesaturn** [comment]
> My intuition would be to use `${FAST_THEME_NAME}alias` not `${FAST_THEME_NAME}command`. If you considered that, what made you choose `${FAST_THEME_NAME}command`?

Oops, I didn't care about highlight color. I agree with you to use `${FAST_THEME_NAME}alias`!

> How hard do you think it would be to support multi-word abbreviations? Is that possible with F-Sy-H?

In my opinion, it would be slightly difficult because F-Sy-H chroma function seems to be triggered by a single word.
To support multi-word abbreviations, we need to create a chroma function for the first word only, and then the second and subsequent words should be treated like arguments of the first word.

I think therefore that it can be implemented roughly in the following flow.

1. list all abbreviations
2. group by the first word
3. generate chroma function for each first word dynamically using `eval` or something
4. register chroma function for each first word

**Comment by olets** [comment]
Sounds tricky enough that it's not worth letting multi-word highlighting be a blocker for documenting single-word highlighting. For now, let's put single-word out into the world.

If you're interested in contributing to the documentation, please open a PR for https://zsh-abbr.olets.dev/advanced.html#syntax-highlighting. To speed up any PR back-and-forth, I'm picturing something like

```md
#### fast-syntax-highlighting

[fast-syntax-highlighting](https://github.com/zdharma/fast-syntax-highlighting) users…

…

Want highlighting for multi-word aliases? See [#24](https://github.com/olets/zsh-abbr/issues/24).

#### zsh-syntax-highlighting

…
```

If you're not interested in making the change, lmk and I'll make an update!

**Comment by tomoesaturn** [comment]
@ Thanks! I'll try to contribute to the documentation.

**Comment by olets** [comment]
@shimajiteppei would you like to be added as a contributor in the GitHub readme and https://zsh-abbr.olets.dev/community/ *

&nbsp;

* the docs site's GitHub-hosted images don't always load on the first try

**Comment by shimajiteppei** [comment]
@olets Thank you for your offer. I would be happy to be added.

**Comment by olets** [comment]
I've opened #120 to track multi-word abbreviations. Closing

**Comment by 5A6F65** [comment]
Hello @olets @shimajiteppei ,
Thank you very much for your previous contributions. `zsh-abbr` is one of my favorite zsh plugins.

I'm currently working on supporting f-sy-h of multi-word abbreviations, but I've encountered an issue:
For global abbreviations, what should their highlighting behavior be? Command/alias, subcommand, and option don't seem to fit.

Additionally, I haven't come up with a good way to handle prefixes.
Considering that f-sy-h seems to support `sudo`, my current idea is to ignore support for other prefixes.
Do you have any better ideas?

Thank you again for your contributions!

**Comment by olets** [comment]
@5A6F65 cool!

> what should their highlighting behavior be

Maybe match alias? Or document how a user could choose for themselves.

> prefixes

Hm good question. The current zsh-syntax-highlighting snippets don't support prefixes. Not supporting them for fast-syntax-highlighting seems fine. Can always be enhanced in the future

//

Best place to continue discussing is

- #120
