### ISSUE TITLE
SHA256 Mismatch

### ISSUE THREAD

**Issue by drewauff** [olets/zsh-abbr#27]
Homebrew
iTerm2
MacOS Catalina
===================

error is as follows:

==> Installing zsh-abbr from olets/tap
==> Downloading https://github.com/olets/zsh-abbr/releases/download/v4.1.0/v4.1.0.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/167840485/a486e300-1620-11eb-94a5-c244f3169fc6?X-Amz-Algorithm=AWS4-HMAC-S
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 44fafc4a873beb7d6df9065836caa0187acb3965
  Actual: bacc95a9c65faf851a3009641885fae0b2ae9a80ade1aa7892e200ee6c399294
 Archive: /Users/USERNAMEREDACTED/Library/Caches/Homebrew/downloads/be31d708fcd84ff43e0cdd759ce4234827c06f437125a37858ff364650658ea3--v4.1.0.tar.gz
To retry an incomplete download, remove the file above.

I removed the file mbut it makes no difference.

**Comment by olets** [comment]
Thanks for reporting!

Interesting. 44fafc4 is what the Homebrew formula file had.

I've cut a hotfix release 4.1.1. No changes, just a chance to give Homebrew a fresh SHA. Let me know if that doesn't fix the problem

**Comment by drewauff** [comment]
==> Installing zsh-abbr from olets/tap
==> Downloading https://github.com/olets/zsh-abbr/releases/download/v4.1.1/v4.1.1.tar.gz
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "zsh-abbr"
Download failed: https://github.com/olets/zsh-abbr/releases/download/v4.1.1/v4.1.1.tar.gz

**Comment by olets** [comment]
That one was clearly my fault. Missed uploading the archive. Getting married soon and must have been thinking about that!

Uploaded the file, so the new error should be cleared. But now Homebrew's giving me the SHA mismatch error, with an "actual" of `843b7a90f98d89c4de3821d8386229c0246b1e8ee3df8ecc9defcbf108238cec`. Still not sure why that's happening.

Let me know if it works for you, and thanks for bearing with this!

**Comment by drewauff** [comment]
brew install olets/tap/zsh-abbr
==> Installing zsh-abbr from olets/tap
==> Downloading https://github.com/olets/zsh-abbr/releases/download/v4.1.1/v4.1.1.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/167840485/5408d180-190f-11eb-80a6-11c63921e2fa?X-Amz-Algorithm=AWS4-HMAC-S
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: b840b4868f541601430281f53fae305cbecf4706
  Actual: 843b7a90f98d89c4de3821d8386229c0246b1e8ee3df8ecc9defcbf108238cec
 Archive: /Users/drewauff/Library/Caches/Homebrew/downloads/b92d3a91eff3425e5b398b27404a9db4af82b1bd90efbcea2c1cedb60f8bad64--v4.1.1.tar.gz
To retry an incomplete download, remove the file above.

**Comment by drewauff** [comment]
I removed the file and tried again .. same result

**Comment by olets** [comment]
Deleting didn't help for me either. At least our errors have the same "actual".

**Comment by drewauff** [comment]
could it be an issue with Homebrew?

**Comment by olets** [comment]
Fixed. #pre-wedding-brain. Go ahead and close if it works for you

**Comment by drewauff** [comment]
lol.. Awesome, thanks 👍
