### ISSUE TITLE
Tabbing for abbrs does not work anymore

### ISSUE THREAD

**Issue by modularTaco** [olets/zsh-abbr#34]
Hey,

i updated my fedora system yesterday from 31 to 32.

Before the update it was possible for me to use the abbreviations via tabbing. E.g. typing `vp`, hitting TAB and zsh shows my abbreviation `vprov` (for `vagrant provision`).  
Since the update this is no longer the case.  
The abbreviations work as expected (typing `vprov` auto-expands to `vagrant provision` after hitting space or enter).  
I'm not sure where i have too look for the cause of this issue.

```
➜ abbr version
zsh-abbr version 4.2.0

➜ zsh --version
zsh 5.8 (x86_64-redhat-linux-gnu
```

Reinstalled abbr already (installed via brew now), but this has not fixed the issue.

**Comment by olets** [comment]
zsh-abbr doesn't support tab completion of abbreviations. That must have come as a side effect of some other plugin. Maybe a history completion plugin? Or an alias completion plugin and you had aliases duplicating your abbreviations? Don't know why a system upgrade would have change that behavior though. Lmk if you figure it out!

(Unasked for sticking my nose in but from the limited info I have sounds like `abbr vp="vagrant provision"` might be helpful 😃)

Closing this but if you do track it down to a zsh-abbr bug you're welcome to reopen
