### ISSUE TITLE
Abbreviations do not expand [oh-my-zsh]

### ISSUE THREAD

**Issue by zohnannor** [olets/zsh-abbr#46]
I've installed `zsh-abbr` using `oh-my-zsh`:

```zsh
$ git clone https://github.com/olets/zsh-abbr.git  ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-abbr
```

And added it to my plugins list in `.zshrc`:

```zsh
plugins=(
    git
    common-aliases
    ---snip---
    zsh-syntax-highlighting
    zsh-abbr
)
source $ZSH/oh-my-zsh.sh
```

Then I ran `abbr import-aliases` and they were successfully imported, but weren't working even after I restarted `zsh`, commented out all the other plugins I have and re-imported aliases.

The solution to this problem is just

```zsh
$ source $ZSH_CUSTOM/plugins/zsh-abbr/zsh-abbr.zsh
```

but isn't there more elegant solution? Should I just add the line above to my `.zshrc`? (I thought `oh-my-zsh` were doing exactly that -- `source`ing plugins' scripts?)

**Comment by olets** [comment]
Thanks for reporting!

I thought so too, but I don't use OMZ and don't know its inner workings especially well.

Lots on my plate right now; I'll shoot to investigate in the next few weeks! Let me know if you figure out anything in the meantime.

**Comment by zohnannor** [comment]
No problem, thanks!
I will try to figure out the problem myself, and if I find anything, I will definitely let you know.

**Comment by zohnannor** [comment]
Apparently the reason for OMZ isn't working as expected is it needs to be `source`d after the `bindkey -v` line I had in my `.zshrc`.

I also apologize for a late response for such an easy issue solution. The solution is simply to move `source $ZSH/oh-my-zsh.sh` line in the `.zshrc` to the bottom of the file!

**Comment by olets** [comment]
No apology needed! Glad you got it working

**Comment by olets** [comment]
@k3n interesting. Moving that to a new issue

- #149

**Comment by justrajdeep** [comment]
I kept getting this error 

```
$zsh
abbr: Finishing installing dependencies
abbr: There was a problem finishing installing dependencies
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? acompinit: initialization aborted
```

this was a simpler solution to fix it https://dev.to/frost/fish-style-abbreviations-in-zsh-40aa

**Comment by olets** [comment]
@justrajdeep thanks for reporting. I'd like to learn more about your setup, so that I can try to resolve the problem you found.

I think it is unrelated to this oh-my-zsh issue. I think it's related to

- #156

but that issue is also closed. If you're up for helping me diagnose the problem, please [open a new issue](https://github.com/olets/zsh-abbr/issues/new?template=bug_report.yml).

//

If the alias-based solution you linked has only a subset of zsh-abbr's features, but if it meets your need that's great!

**Comment by justrajdeep** [comment]
hi @olets 

I just posted here so that in case someone come upto this thread facing the same issue they have a solution.

I have a very non-standard installation of linux so might be hard to replicate and fix, let me know what info you would need from my end i can provide them.

**Comment by olets** [comment]
Thanks! If you open a new issue and choose the "bug report" template, you'll be prompted with a list of questions that will help me.
