### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ervinpopescu** [olets/zsh-abbr#54]
```
_abbr_job_push:add_job:7: permission denied: /tmp/zsh-abbr/jobs/1646859860.17046
_abbr_job_push:wait_turn:3: bad math expression: operand expected at end of string
```

I don't really know any other way to describe this but segfault :) 

```
'builtin' 'echo' $job_description > ${ABBR_TMPDIR}jobs/$job_name
next_job_age=$(( $(date +%s) - ${next_job%.*} ))
```

These are the two problematic lines. Looks like the second one is caused by the first.
I don't really know what to do about that `permission denied`. Denied by what? Permissions?

**Comment by ervinpopescu** [comment]
Solved... I've used the same plugin with the root account and apparently the tmp folder has been modified/created as root.
I don't think this is the best practice tho. Do I have to source a different `zsh-abbr.zsh`?

**Comment by ervinpopescu** [comment]
Solved... I've used the same plugin with the root account and apparently the tmp folder has been modified/created as root.
I don't think this is the best practice tho. Do I have to source a different `zsh-abbr.zsh`?

**Comment by olets** [comment]
Thanks for the report!

> I've used the same plugin with the root account and apparently the tmp folder has been modified/created as root

Aha. That makes sense I think.

The immediate fix is to delete the directory `/tmp/zsh-abbr/jobs` and then reinitialize the shell (`exec zsh`). When the plugin initializes it will recreate the directory.

Would be nice if the zsh-abbr handled this case, but my gut says it would be tricky to implement well. Some sort of per-permission-level file, and each session tracks down the right one? Don't want to do anything with changing file permissions, feels like that could open attack vectors.

Instead I think we can work around it with user configuration: in your `.zshrc` before loading the plugin, customize ABBR_TMPDIR to use a directory that can be read and written to by root and your other user(s):

```shell
# ~/.zshrc
ABBR_TMPDIR=some/directory/root-and-nonroot/can-write/to
# and then load zsh-abbr
```

Let me know if that works!

**Comment by ervinpopescu** [comment]
> The immediate fix is to delete the directory /tmp/zsh-abbr/jobs and then reload the shell (exec zsh). When the plugin initializes it will recreate the directory. 

Yep did just that yesterday.

> Instead I think we can work around it with user configuration: in your .zshrc before loading the plugin, customize ABBR_TMPDIR to use a directory that can be read and written to by root and your other user(s):
> ```
> # ~/.zshrc
> ABBR_TMPDIR=some/directory/root-and-nonroot/can-write/to
> # and then load zsh-abbr
> ```
> Let me know if that works!

That's an interesting approach. Will test, **thanks**!

**Comment by olets** [comment]
Hi @ervinpopescu I revisited this, and built a separate-directories solution in v5.6.0.

Lmk if you'd like to be added to https://github.com/olets/zsh-abbr#community and https://zsh-abbr.olets.dev/community/ for the bug report and thinking through the solution. If so I'll have the all-contributors bot open a pull request. I'll tag you in it, and you'll need to review before I merge to make sure the bot pulled the right info.

**Comment by ervinpopescu** [comment]
Hi @olets, that sounds great and all, but I really don't think that's needed, the solution for this was mostly driven by you, so I am good with staying in the shadows :) 

Thanks for the proposal though!
