### ISSUE TITLE
Could you publish tarball for v4.8.2?

### ISSUE THREAD

**Issue by Sixeight** [olets/zsh-abbr#66]
There is no tar ball for [v4.8.2](https://github.com/olets/zsh-abbr/releases/tag/v4.8.2
) on GitHub Releases.
Please publish the new version.

[Formula](https://github.com/olets/homebrew-tap/commit/1e24f19ff1a0b04e31728bfe1a20b781be2541d0) specifies an URL below, but the file is not found.
https://github.com/olets/zsh-abbr/releases/download/v4.8.2/v4.8.2.tar.gz

**Comment by olets** [comment]
Fixed! Thanks for the report
