### ISSUE TITLE
zsh-autosuggestions' suggestions don't clear after the line is accepted

### ISSUE THREAD

**Issue by Icy-Thought** [olets/zsh-abbr#67]
I do apologize if zsh-abbr is not at fault here, I am still a ZSH newbie who recently migrated from Fish..

What I am here to report today is that when`bindkey -M main "^M" abbr-expand-and-accept` is used, the suggestions provided by [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) would still be printed after the entered command even though it was never accepted.

![image](https://user-images.githubusercontent.com/53710398/207923610-039b1085-2f9c-4261-bd70-8709285f8cfd.png)

And after some experimentation + searching I stumbled upon `bindkey -M main "^M" accept-line` which happens to solve the issue but at the cost of having no abbr on <kbd>Enter</kbd>.

Before <kbd>Enter</kbd>:
![image](https://user-images.githubusercontent.com/53710398/207924372-df9c795b-2721-4b7d-a206-29ee52bcf532.png)

After <kbd>Enter</kbd>:
![image](https://user-images.githubusercontent.com/53710398/207924259-31ff4808-e241-4432-81a9-b6e8acf59191.png)

I obviously do not know what the appropriate solution to this issue is and therefore I am here to request help from someone who is more knowledgeable than myself!

**Comment by olets** [comment]
Thanks for the report!

I was able to replicate this.

Possibly a zsh-autosuggestions bug, possible I'm misunderstanding how to use the tools zsh-autosuggestions provides for clearing suggestions. I've opened a zsh-autosuggestions issue. Labelling this issue "needs more info" not because I need info from you but because I need info from zsh-autosuggestions.

- https://github.com/zsh-users/zsh-autosuggestions/issues/716

**Comment by Icy-Thought** [comment]
Good to know! Also, thank you for putting in the time and effort to solve this issue!

**Comment by olets** [comment]
Figured it out. Should be fixed in https://github.com/olets/zsh-abbr/releases/tag/v4.8.3 and https://github.com/olets/zsh-abbr/releases/tag/v5.0.0.beta-3. Let me know if it continues to give you trouble!

**Comment by Icy-Thought** [comment]
Will do! And thanks again for fixing it! :)

**Comment by Icy-Thought** [comment]
Just installed + tested the latest release and I can confirm that this issue has indeed been resolved! :tada: 

Closing this issue since no further investigation/fixes are required.

**Comment by olets** [comment]
Belatedly acknowledging more contributors in https://github.com/olets/zsh-abbr#community and https://zsh-abbr.olets.dev/community/

Would you like to be added @Icy-Thought? If so, I'll have the all-contributors bot open a pull request. Then I'll tag you in it to review for correct info

**Comment by Icy-Thought** [comment]
I guess I could be added to the site with the packaging tag? :shrug: 

Was planning on migrating `zsh-abbr` to Guix after migrating anyways since I noticed it was missing from the packages list.

**Comment by olets** [comment]
Ok how about this: if that happens we revisit. Thanks!

**Comment by Icy-Thought** [comment]
Sure thing! I already maintain the nixpkg btw! 😉

**Comment by olets** [comment]
Oh nice! I've added that to the docs https://zsh-abbr.olets.dev/installation.html#linux-package-repositories

Want to acknowledged in the Community list for that?

**Comment by Icy-Thought** [comment]
Hehe. I should've mentioned it earlier! xD
If you feel I should be there, add me. :blush:

**Comment by olets** [comment]
@all-contributors please add @Icy-Thought  for platform.

@Icy-Thought review the PR the bot posts below 👇 to see if the info it pulls is right
