### ISSUE TITLE
`abbr c` does not clear abbreviations created with the pattern `abbr x=y`

### ISSUE THREAD

**Issue by metruzanca** [olets/zsh-abbr#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Update the issue title

- [X] I have updated the title

### Expected Behavior

When running `abbr c` / `abbr clear-session` I'm expecting all abbr to be wiped. My use case being to run `abbr c; abbr import-aliases` to get rid of old and add new aliases to abbr.

### Actual Behavior

<img width="272" alt="Screenshot 2023-04-19 at 11 59 47 AM" src="https://user-images.githubusercontent.com/32832892/233133864-4112c890-9e49-4a1a-9c2b-55f681b1c5d0.png">

All other commands seem to work fine. The actual plugin works as expected, its just deleting the abbr which is tedious. I can delete with `abbr erase <name>`, just not abbr c.

### Steps To Reproduce

Basic zsh install (no oh-my-zsh) w/ Zplug as the plugin manager running on MacOS ventura.

### Environment

```shell
zsh-abbr version 5.0.1
zsh 5.9 (arm-apple-darwin22.1.0)
OSTYPE darwin22.0
```

### Installation method

Other

### Installation method details

```bash
brew tap "olets/tap"
brew install zplug olets/tap/zsh-abbr # & zsh of course
```

ZPlug setup
```zsh
#!/usr/bin/env zsh
# as a part of your dotfiles setup/linking/stowing script
source /opt/homebrew/opt/zplug/init.zsh;
zplug "olets/zsh-abbr";
zplug install;
```

```zsh
# .zshrc
source /opt/homebrew/opt/zplug/init.zsh;
zplug "olets/zsh-abbr";
zplug load;
```

**Comment by olets** [comment]
`clear-session` clears all _session_ abbreviations https://zsh-abbr.olets.dev/scopes.html#session (closing the terminal, or restarting zsh `exec zsh` does too)

If session abbreviations work for you, import aliases with `abbr -S import-aliases`. Then `abbr c` will clear them.

If you want to clear all _user_ abbreviations, two good (though destructive) options are to delete everything from `$ABBR_USER_ABBREVIATIONS_FILE`

```shell
echo > $ABBR_USER_ABBREVIATIONS_FILE
```

or to delete the file

```shell
rm $ABBR_USER_ABBREVIATIONS_FILE
# or, if you want to be able to recover the file, use https://github.com/sindresorhus/trash-cli
```

**Comment by olets** [comment]
I'm taking that reaction as good news that this solved your issue. I updated the title to be more specific now that we know what he problem was. Thanks for bringing this up!

**Comment by metruzanca** [comment]
Yes sorry I forgot to finish my reply. This was exactly what i wanted. I'm moving my setup to use sessions now.

Thanks for the great reply and thanks for the great plugin.
